FROM node:19.1.0
COPY ecomm-frontend/ /src/app/ecom/
WORKDIR /src/app/ecom/
RUN npm install -g npm@8.19.3
RUN npm install
RUN chmod +x node_modules/.bin/react-scripts
RUN npm run build
RUN npm install -g serve

EXPOSE 3000
ENTRYPOINT ["serve", "-s", "build"]
