apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: saecom
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: postgres-storage-class
  resources:
    requests:
      storage: 2Gi
