apiVersion: v1
kind: Service 
metadata:
  name: ecomm-frontend-service
  namespace: saecom
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - targetPort: 3000
    port: 3000
